FROM node:20-alpine

WORKDIR /app

RUN npm install -g tsx

COPY package*.json ./

RUN apk add --no-cache python3 make g++ pkgconfig cairo-dev pango-dev jpeg-dev giflib-dev
RUN npm ci

COPY src ./src

RUN echo "0 9 * * * tsx /app/src/services/anomalyService.ts >> /var/log/anomaly.log 2>&1" > /etc/crontabs/root

CMD ["crond", "-f", "-l", "2"]